project:
  type: website
  output-dir: docs

website:
  title: "STAA 566 Data Viz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ggplot2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

