project:
  type: website

website:
  title: "STAA 566 Data Viz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ggplot2.qmd
        text: ggplot2
      - href: dynamic.qmd
        text: dynamic graphs
      - href: maps.qmd
        text: maps
      - href: tables.qmd
        text: tables
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

